baseURL = "https://koishichito.github.io/quickstart2/"
languageCode = "ja"
title = "発禁愚"
contentDir = "post"
disableKinds = ["RSS", "sitemap"]
publishDir = "docs"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
[taxonomies]
tag = "tags"
